name: senai_automacao
run-name: ${{ github.actor }} Pipeline Deploy 🐝👑
on: 
  push:
    branches:
      - "develop"
    paths-ignore:
      - "docs/**"
      - "images/**"
      - "*.md"
      - "*.dockerignore"
jobs:
  setup-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS CLI
        if: always()
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Test AWS CLI
        if: always()
        run: aws sts get-caller-identity

      - name: Checkout code
        if: always()
        uses: actions/checkout@v3

      - name: Install AWS CLI
        if: always()
        uses: aws-actions/aws-cli@v2

      - name: Run sync script
        if: always()
        run: |
          file_system_id=${{ secrets.EFS_FILE_SYSTEM_ID }}
          if aws efs describe-file-systems --file-system-id $file_system_id | jq -r '.FileSystems[].LifeCycleState' | grep -q available; then
            sudo aws efs mount --file-system-id $file_system_id:/ /mnt/efs
            sudo rsync -avz ./images/ /mnt/efs/
            sudo umount /mnt/efs
          else
            echo "EFS File System is not available. Skipping sync."
          fi