name: senai_automacao
run-name: ${{ github.actor }} Pipeline Deploy 🐝👑
on: 
  push:
    branches:
      - "develop"
    paths-ignore:
      - "*.txt"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: INSTALL PACKAGES
        run: |
          sudo apt update -y
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/

      - name: Configure AWS CLI
        if: always()
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Test AWS CLI
        if: always()
        run: aws sts get-caller-identity
      
      - name: Snyk Auth
        run: |
          snyk -d auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}

      - name: Run sync script
        if: always()
        run: |
          file_system_id=${{ secrets.EFS_FILE_SYSTEM_ID }}
          if aws efs describe-file-systems --file-system-id $file_system_id | jq -r '.FileSystems[].LifeCycleState' | grep -q available; then
            sudo aws efs mount --file-system-id $file_system_id:/ /efs
            sudo rsync -avz ./images/ /efs/
            sudo umount /efs
          else
            echo "EFS File System is not available. Skipping sync."
          fi