name: senai_automacao
run-name: ${{ github.actor }} Pipeline Deploy 🐝👑
on: 
  push:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
      - "images/**"
      - "*.md"
      - "*.dockerignore"
jobs:
  githubactions-senai:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
      - name: sync-images
        uses: actions/checkout@v3
      - name: Install awscli
        uses: aws-actions/aws-cli@v2
      - name: Run sync script
        run: |
          aws efs describe-file-systems | jq -r '.FileSystems[].LifeCycleState' | grep -q available
          if [[ $? -eq 0 ]]; then
            sudo aws efs mount file-system-id:fs-0ffa25d8387046409 /efs
            rsync -avz ./images/ /efs
            sudo aws efs umount /efs
          else
            echo "EFS File System is not available. Skipping sync."
          fi
        env:
          EFS_FILE_SYSTEM_ID: ${{ secrets.EFS_FILE_SYSTEM_ID }}
